### ISSUE TITLE
Too many files open

### ISSUE THREAD

**Issue by OfficeGeek888** [ipfs/ipfs-desktop#1337]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.10.2
- **Electron Version**: 7.1.2
- **Chrome Version**: 78.0.3904.113

**Error**

```
Error: EMFILE: too many open files, open 'C:\Users\Noah Bangs\AppData\Roaming\IPFS Desktop\config.json'
    at Object.openSync (fs.js:447:3)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.readFileSync (fs.js:349:35)
    at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
    at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
    at ElectronStore.get store [as store] (C:\Users\Noah Bangs\AppData\Local\Programs\IPFS Desktop\resources\app.asar\node_modules\conf\index.js:411:18)
    at ElectronStore.set (C:\Users\Noah Bangs\AppData\Local\Programs\IPFS Desktop\resources\app.asar\node_modules\conf\index.js:307:10)
    at BrowserWindow.<anonymous> (C:\Users\Noah Bangs\AppData\Local\Programs\IPFS Desktop\resources\app.asar\out\webui\index.js:60:23)
    at BrowserWindow.emit (events.js:203:13)
```

**Comment by SgtPooki** [comment]
@OfficeGeek888 I apologize for the delay in responding to you. This error hasn't popped up in our issue queue since you originally opened this and should be resolved.
