### ISSUE TITLE
TypeError: Object has been destroyed

### ISSUE THREAD

**Issue by JoeyTWhite** [ipfs/ipfs-desktop#1486]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.11.2
- **Electron Version**: 8.2.4
- **Chrome Version**: 80.0.3987.165

**Error**

```
TypeError: Object has been destroyed
    at updateMenu (D:\IPFS Desktop\resources\app.asar\src\tray.js:306:12)
    at IpcMainImpl.<anonymous> (D:\IPFS Desktop\resources\app.asar\src\tray.js:323:5)
    at IpcMainImpl.emit (events.js:215:7)
    at updateStatus (D:\IPFS Desktop\resources\app.asar\src\daemon\index.js:17:13)
    at startIpfs (D:\IPFS Desktop\resources\app.asar\src\daemon\index.js:69:7)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by lidel** [comment]
Please upgrade to [v0.13.2](https://github.com/ipfs-shipyard/ipfs-desktop/releases/tag/v0.13.2)

**Comment by JoeyTWhite** [comment]
Same problem.

Marcin Rataj <notifications@github.com> 于2020年10月13日周二 上午2:14写道：

**Comment by lidel** [comment]
I and was unable to reproduce. I thought this could be related to custom path and installed IPFS Desktop to `c:\IPFS Desktop`, but it works fine.

@JoeyTWhite are you able to provide us with steps how to reproduce this error?
Sharing contents of `combined.log` from `Advanced` → `Open Logs Directory` would also help.
