### ISSUE TITLE
Error reported by IPFS Desktop

### ISSUE THREAD

**Issue by davidfsol5** [ipfs/ipfs-desktop#1785]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.13.2
- **Electron Version**: 9.3.2
- **Chrome Version**: 83.0.4103.122

**Error**

```
TypeError: Cannot read property 'pid' of null
    at Timeout._onTimeout (C:\Program Files\IPFS Desktop\resources\app.asar\node_modules\ipfsd-ctl\src\ipfsd-daemon.js:242:101)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

**Comment by lidel** [comment]
This should be fixed since 0.14, please update to  [v0.15.0](https://github.com/ipfs/ipfs-desktop/releases/tag/v0.15.0).
