### ISSUE TITLE
IPFS-Desktop-Windows启动失败

### ISSUE THREAD

**Issue by DancGo** [ipfs/ipfs-desktop#1798]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.14.0
- **Electron Version**: 11.2.3
- **Chrome Version**: 87.0.4280.141

**Error**

```
Error: Command failed with EPERM: D:\IPFS Desktop\resources\app.asar.unpacked\node_modules\go-ipfs\go-ipfs\ipfs.exe daemon --migrate --enable-gc --routing dhtclient
spawn EPERM
    at ChildProcess.spawn (internal/child_process.js:407:11)
    at Object.spawn (child_process.js:557:9)
    at execa (D:\IPFS Desktop\resources\app.asar\node_modules\ipfsd-ctl\node_modules\execa\index.js:80:26)
    at D:\IPFS Desktop\resources\app.asar\node_modules\ipfsd-ctl\src\ipfsd-daemon.js:196:27
    at new Promise (<anonymous>)
    at Daemon.start (D:\IPFS Desktop\resources\app.asar\node_modules\ipfsd-ctl\src\ipfsd-daemon.js:195:21)
    at module.exports (D:\IPFS Desktop\resources\app.asar\src\daemon\daemon.js:77:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async startIpfs (D:\IPFS Desktop\resources\app.asar\src\daemon\index.js:54:15)
    at async module.exports (D:\IPFS Desktop\resources\app.asar\src\daemon\index.js:116:3)
```

**Comment by lidel** [comment]
Duplicate, let's continue in https://github.com/ipfs/ipfs-desktop/issues/1803#issuecomment-832346608
