### ISSUE TITLE
unknown error

### ISSUE THREAD

**Issue by bes-ptah** [ipfs/ipfs-desktop#1806]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.14.0
- **Electron Version**: 11.2.3
- **Chrome Version**: 87.0.4280.141

**Error**

```
Error: EPERM: operation not permitted, open 'C:\Users\skyte\.ipfs-desktop\IPFS_PATH'
    at Object.openSync (fs.js:466:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1812)
    at Object.writeFileSync (fs.js:1366:35)
    at Object.outputFileSync (C:\Program Files\IPFS Desktop\resources\app.asar\node_modules\fs-extra\lib\output\index.js:31:15)
    at writeIpfsPath (C:\Program Files\IPFS Desktop\resources\app.asar\src\daemon\index.js:130:6)
    at startIpfs (C:\Program Files\IPFS Desktop\resources\app.asar\src\daemon\index.js:50:7)
    at module.exports (C:\Program Files\IPFS Desktop\resources\app.asar\src\daemon\index.js:116:9)
    at run (C:\Program Files\IPFS Desktop\resources\app.asar\src\index.js:74:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by lidel** [comment]
@bes-ptah for some reason the user running IPFS Desktop has no rights to write or read to `C:\Users\skyte\.ipfs-desktop\IPFS_PATH`. Try removing `C:\Users\skyte\.ipfs-desktop`, then updating to  [v0.15.0](https://github.com/ipfs/ipfs-desktop/releases/tag/v0.15.0)  and reopen if this did not help.
