### ISSUE TITLE
Unable to open .ipfs-desktop\IPFS_PATH after installing

### ISSUE THREAD

**Issue by Cyber5an** [ipfs/ipfs-desktop#1846]
I installed the app and every run gives me fatal error

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.15.1
- **Electron Version**: 12.0.5
- **Chrome Version**: 89.0.4389.128

**Error**

```
Error: EPERM: operation not permitted, open 'C:\Users\CyberSan\.ipfs-desktop\IPFS_PATH'
    at Object.openSync (fs.js:476:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1846)
    at Object.writeFileSync (fs.js:1467:35)
    at Object.outputFileSync (C:\Program Files\IPFS Desktop\resources\app.asar\node_modules\fs-extra\lib\output\index.js:31:15)
    at writeIpfsPath (C:\Program Files\IPFS Desktop\resources\app.asar\src\daemon\index.js:130:6)
    at startIpfs (C:\Program Files\IPFS Desktop\resources\app.asar\src\daemon\index.js:50:7)
    at module.exports (C:\Program Files\IPFS Desktop\resources\app.asar\src\daemon\index.js:116:9)
    at run (C:\Program Files\IPFS Desktop\resources\app.asar\src\index.js:74:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by Cyber5an** [comment]
Removing folder .ipfs-desktop from user home makes IPFS work again.
