### ISSUE TITLE
IPFS Desktop Crash

### ISSUE THREAD

**Issue by unbeatable-101** [ipfs/ipfs-desktop#1855]
Please describe what you were doing when this error happened.

Checking for updates

**Specifications**

- **OS**: darwin
- **IPFS Desktop Version**: 0.15.1
- **Electron Version**: 12.0.5
- **Chrome Version**: 89.0.4389.128

**Error**

```
TypeError: ctx.manualCheckForUpdates is not a function
    at click (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/tray.js:216:30)
    at MenuItem.click (electron/js2c/browser_init.js:73:1742)
    at Object.a._executeCommand (electron/js2c/browser_init.js:81:2492)
```

**Comment by lidel** [comment]
@unbeatable-101 can you please attach your logs?

1. From the "IPFS icon" menu in your menubar/system tray, go to `Advanced` → `Open Logs Directory` *(for Linux users who do not have this menu, logs can be found in `$HOME/.config/IPFS Desktop` )*
2. Find `*.log` files
3. Attach `error.log` and `combined.log` to this issue.

**Comment by unbeatable-101** [comment]
[combined.log](https://github.com/ipfs/ipfs-desktop/files/6705050/combined.log)
[error.log](https://github.com/ipfs/ipfs-desktop/files/6705051/error.log)

**Comment by unbeatable-101** [comment]
I don't know, since I have been using https://github.com/ipfs-shipyard/go-ipfs-desktop.

I'll download again and see.

**Comment by unbeatable-101** [comment]
It doesn't seem to happen
