### ISSUE TITLE
Stuck on "is Starting" then crash if click "check on updates"

### ISSUE THREAD

**Issue by Mamky-Ebal** [ipfs/ipfs-desktop#1869]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.16.0
- **Electron Version**: 13.1.4
- **Chrome Version**: 91.0.4472.106

**Error**

```
TypeError: ctx.manualCheckForUpdates is not a function
    at click (C:\Program Files\IPFS Desktop\resources\app.asar\src\tray.js:216:30)
    at MenuItem.click (electron/js2c/browser_init.js:73:1742)
    at Object.a._executeCommand (electron/js2c/browser_init.js:81:2492)
```

**Comment by lidel** [comment]
@Mamky-Ebal   Is this a clean install or did you have a big repository?
