### ISSUE TITLE
no title

### ISSUE THREAD

**Issue by tuser-code** [ipfs/ipfs-desktop#1870]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: linux
- **IPFS Desktop Version**: 0.16.0
- **Electron Version**: 13.1.4
- **Chrome Version**: 91.0.4472.106

**Error**

```
Error: EACCES: permission denied, open '/home/enes/snap/ipfs-desktop/26/.config/IPFS Desktop/config.json'
    at Object.openSync (fs.js:476:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1846)
    at Object.writeFileSync (fs.js:1467:35)
    at ElectronStore._write (/snap/ipfs-desktop/26/resources/app.asar/node_modules/conf/dist/source/index.js:370:16)
    at ElectronStore.set store [as store] (/snap/ipfs-desktop/26/resources/app.asar/node_modules/conf/dist/source/index.js:296:14)
    at ElectronStore.set (/snap/ipfs-desktop/26/resources/app.asar/node_modules/conf/dist/source/index.js:189:20)
    at Timeout.existsAndUpdate [as _onTimeout] (/snap/ipfs-desktop/26/resources/app.asar/src/npm-on-ipfs/index.js:38:11)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

**Comment by Stebalien** [comment]
> Please describe what you were doing when this error happened.
