### ISSUE TITLE
[gui error report]

### ISSUE THREAD

**Issue by ykargin** [ipfs/ipfs-desktop#1892]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.16.2
- **Electron Version**: 13.1.7
- **Chrome Version**: 91.0.4472.124

**Error**

```
Error: Command failed with UNKNOWN: C:\Users\optio\AppData\Local\Programs\IPFS Desktop\resources\app.asar.unpacked\node_modules\go-ipfs\go-ipfs\ipfs.exe daemon --migrate --enable-gc --routing dhtclient
spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:403:11)
    at Object.spawn (child_process.js:562:9)
    at execa (C:\Users\optio\AppData\Local\Programs\IPFS Desktop\resources\app.asar\node_modules\ipfsd-ctl\node_modules\execa\index.js:80:26)
    at C:\Users\optio\AppData\Local\Programs\IPFS Desktop\resources\app.asar\node_modules\ipfsd-ctl\src\ipfsd-daemon.js:196:27
    at new Promise (<anonymous>)
    at Daemon.start (C:\Users\optio\AppData\Local\Programs\IPFS Desktop\resources\app.asar\node_modules\ipfsd-ctl\src\ipfsd-daemon.js:195:21)
    at module.exports (C:\Users\optio\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\daemon\daemon.js:77:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async startIpfs (C:\Users\optio\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\daemon\index.js:54:15)
    at async module.exports (C:\Users\optio\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\daemon\index.js:116:3)
```

**Comment by lidel** [comment]
It looks like you don't have access rights  for some reason, or there is a disk corruption.

Things to try:
- Try running as an administrator or change permissions to `C:\Users\optio\AppData\Local\Programs\IPFS Desktop` 
- Uninstall IPFS Desktop, remove `C:\Users\optio\AppData\Local\Programs\IPFS Desktop`   and install it again

lmk if any of the above helped

**Comment by ykargin** [comment]
Hi Lidel, for now i have try to run as administrator - same issue. Anyway no permissions has been changed since previous (working) version, and issue faced directly after ipfs desktop upgrade.  I'm going to try reinstall with folder remove....

**Comment by ykargin** [comment]
Well full reinstall helps. if this is one-time-issue i think we can close it
