### ISSUE TITLE
crashed when start

### ISSUE THREAD

**Issue by CrazyBirdie1** [ipfs/ipfs-desktop#1911]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.15.0
- **Electron Version**: 12.0.5
- **Chrome Version**: 89.0.4389.128

**Error**

```
TypeError: ctx.manualCheckForUpdates is not a function
    at click (C:\Program Files\IPFS Desktop\resources\app.asar\src\tray.js:216:30)
    at MenuItem.click (electron/js2c/browser_init.js:73:1742)
    at Object.a._executeCommand (electron/js2c/browser_init.js:81:2492)
```

**Comment by lidel** [comment]
Please manually update to [the latest version](https://github.com/ipfs/ipfs-desktop/releases/latest) –  0.15.0  is an old version with known autoupdate bug on Windows.
