### ISSUE TITLE
[gui error report]

### ISSUE THREAD

**Issue by AllTurnSpace** [ipfs/ipfs-desktop#1958]
closed it and now trying to reopen it but errors every time even on restart

**Specifications**

- **OS**: win64
- **IPFS Desktop Version**: 0.18.1
- **Electron Version**: 13.6.3
- **Chrome Version**: 91.0.4472.164

**Error**

```
Error: Command failed with UNKNOWN: C:\Users\mburg\AppData\Local\Programs\IPFS Desktop\resources\app.asar.unpacked\node_modules\go-ipfs\go-ipfs\ipfs.exe daemon --agent-version-suffix=desktop --migrate --enable-gc --routing=dhtclient
spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:403:11)
    at Object.spawn (child_process.js:562:9)
    at execa (C:\Users\mburg\AppData\Local\Programs\IPFS Desktop\resources\app.asar\node_modules\ipfsd-ctl\node_modules\execa\index.js:80:26)
    at C:\Users\mburg\AppData\Local\Programs\IPFS Desktop\resources\app.asar\node_modules\ipfsd-ctl\src\ipfsd-daemon.js:196:27
    at new Promise (<anonymous>)
    at Daemon.start (C:\Users\mburg\AppData\Local\Programs\IPFS Desktop\resources\app.asar\node_modules\ipfsd-ctl\src\ipfsd-daemon.js:195:21)
    at module.exports (C:\Users\mburg\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\daemon\daemon.js:77:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async startIpfs (C:\Users\mburg\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\daemon\index.js:54:15)
    at async module.exports (C:\Users\mburg\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\daemon\inde

**Comment by lidel** [comment]
@AllTurnSpace sadly that is not actionable – can you provide more information?

What were you doing when this happened? If possible, attach all logs 
1. From the "IPFS icon" menu in your menubar/system tray, go to `Advanced` → `Open Logs Directory` *(for Linux users who do not have this menu, logs can be found in `$HOME/.config/IPFS Desktop` )*
2. Find `*.log` files
3. Attach `error.log` and `combined.log` to this issue.
