### ISSUE TITLE
[gui error report]

### ISSUE THREAD

**Issue by flencrypto** [ipfs/ipfs-desktop#1969]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.18.1
- **Electron Version**: 13.6.3
- **Chrome Version**: 91.0.4472.164

**Error**

```
Error: EPERM: operation not permitted, open 'C:\Users\benfl\.ipfs-desktop\IPFS_PATH'
    at Object.openSync (fs.js:476:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1846)
    at Object.writeFileSync (fs.js:1467:35)
    at Object.outputFileSync (D:\Users\benfl\AppData\Local\Programs\IPFS Desktop\resources\app.asar\node_modules\fs-extra\lib\output\index.js:31:15)
    at writeIpfsPath (D:\Users\benfl\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\daemon\index.js:130:6)
    at startIpfs (D:\Users\benfl\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\daemon\index.js:50:7)
    at module.exports (D:\Users\benfl\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\daemon\index.js:116:9)
    at run (D:\Users\benfl\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\index.js:74:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by lidel** [comment]
@flencrypto did you install IPFS Desktop for a single user, or used admin account to do it for all users?
If you need a quick fix, just remove `C:\Users\benfl\.ipfs-desktop\IPFS_PATH` and try again.

I suspect this problem will go away when we ship https://github.com/ipfs/ipfs-desktop/pull/1948
