### ISSUE TITLE
[gui error report]

### ISSUE THREAD

**Issue by Cceciliaa** [ipfs/ipfs-desktop#1975]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: darwin
- **IPFS Desktop Version**: 0.18.1
- **Electron Version**: 13.6.3
- **Chrome Version**: 91.0.4472.164

**Error**

```
TypeError: ctx.manualCheckForUpdates is not a function
    at click (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/tray.js:216:30)
    at MenuItem.click (electron/js2c/browser_init.js:73:1742)
    at Object.a._executeCommand (electron/js2c/browser_init.js:81:2492)
```

**Comment by lidel** [comment]
@Cceciliaa  please manually update to the [latest release](https://github.com/ipfs/ipfs-desktop/releases/latest) and try again.
(This should be fixed in v0.19.1 or later)
