### ISSUE TITLE
[gui error report]

### ISSUE THREAD

**Issue by luck453** [ipfs/ipfs-desktop#1978]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.18.1
- **Electron Version**: 13.6.3
- **Chrome Version**: 91.0.4472.164

**Error**

```
TypeError: ctx.manualCheckForUpdates is not a function
    at click (C:\Program Files\IPFS Desktop\resources\app.asar\src\tray.js:216:30)
    at MenuItem.click (electron/js2c/browser_init.js:73:1742)
    at Object.a._executeCommand (electron/js2c/browser_init.js:81:2492)
```

**Comment by lidel** [comment]
@luck453 please manually update to [latest release](https://github.com/ipfs/ipfs-desktop/releases/latest) and try again.
