### ISSUE TITLE
[gui error report]

### ISSUE THREAD

**Issue by tuckernickman** [ipfs/ipfs-desktop#1984]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: darwin
- **IPFS Desktop Version**: 0.18.1
- **Electron Version**: 13.6.3
- **Chrome Version**: 91.0.4472.164

**Error**

```
TypeError: Object has been destroyed
    at BrowserWindow.n.loadURL (electron/js2c/browser_init.js:33:1767)
    at IpcMainImpl.<anonymous> (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/webui/index.js:137:14)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by lidel** [comment]
@tuckernickman  please update to the latest version, see https://github.com/ipfs/ipfs-desktop/issues/1980 (tldr: you need to manually apply update from
