### ISSUE TITLE
[gui error report]

### ISSUE THREAD

**Issue by Martinligabue** [ipfs/ipfs-desktop#1987]
Please describe what you were doing when this error happened.

after updating ipfs from AUR, I right clicked the icon in the taskbar and selected "quit", and it appeared the error

**Specifications**

- **OS**: linux
- **IPFS Desktop Version**: 0.18.1
- **Electron Version**: 13.6.3
- **Chrome Version**: 91.0.4472.164

**Error**

```
Error: Failed to load image from path '/opt/IPFS Desktop/resources/app.asar/assets/icons/tray/off-big.png'
    at updateMenu (/opt/IPFS Desktop/resources/app.asar/src/tray.js:341:12)
    at IpcMainImpl.<anonymous> (/opt/IPFS Desktop/resources/app.asar/src/tray.js:360:5)
    at IpcMainImpl.emit (events.js:327:22)
    at updateStatus (/opt/IPFS Desktop/resources/app.asar/src/daemon/index.js:17:13)
    at stopIpfs (/opt/IPFS Desktop/resources/app.asar/src/daemon/index.js:79:5)
    at App.<anonymous> (/opt/IPFS Desktop/resources/app.asar/src/daemon/index.js:113:22)
    at App.emit (events.js:327:22)
    at click (/opt/IPFS Desktop/resources/app.asar/src/tray.js:236:26)
    at MenuItem.click (electron/js2c/browser_init.js:73:1742)
    at Object.a._executeCommand (electron/js2c/browser_init.js:81:2492)
```

**Comment by RubenKelevra** [comment]
@lidel Well, the building process hasn't changed between 0.18.x and 0.19.x apart from your recommended changes:

https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=ipfs-desktop&id=c78e9755e927f28ee4ab49014f0655942a97915f

Do you think this change could have caused that?

**Comment by RubenKelevra** [comment]
Not sure if this is helpful, but that's the list of files inside a package after building:

```
ipfs-desktop /opt/
ipfs-desktop /opt/IPFS Desktop/
ipfs-desktop /opt/IPFS Desktop/chrome-sandbox
ipfs-desktop /opt/IPFS Desktop/chrome_100_percent.pak
ipfs-desktop /opt/IPFS Desktop/chrome_200_percent.pak
ipfs-desktop /opt/IPFS Desktop/chrome_crashpad_handler
ipfs-desktop /opt/IPFS Desktop/icudtl.dat
ipfs-desktop /opt/IPFS Desktop/ipfs-desktop
ipfs-desktop /opt/IPFS Desktop/libEGL.so
ipfs-desktop /opt/IPFS Desktop/libGLESv2.so
ipfs-desktop /opt/IPFS Desktop/libffmpeg.so
ipfs-desktop /opt/IPFS Desktop/libvk_swiftshader.so
ipfs-desktop /opt/IPFS Desktop/libvulkan.so.1
ipfs-desktop /opt/IPFS Desktop/locales/
ipfs-desktop /opt/IPFS Desktop/locales/am.pak
ipfs-desktop /opt/IPFS Desktop/locales/ar.pak
ipfs-desktop /opt/IPFS Desktop/locales/bg.pak
ipfs-desktop /opt/IPFS Desktop/locales/bn.pak
ipfs-desktop /opt/IPFS Desktop/locales/ca.pak
ipfs-desktop /opt/IPFS Desktop/locales/cs.pak
ipfs-desktop /opt/IPFS Desktop/locales/da.pak
ipfs-desktop /opt/IPFS Desktop/locales/de.pak
ipfs-desktop /opt/IPFS Desktop/locales/el.pak
ipfs-desktop /opt/IPFS Desktop/locales/en-GB.pak
ipfs-desktop /opt/IPFS Desktop/locales/en-US.pak
ipfs-desktop /opt/IPFS Desktop/locales/es-419.pak
ipfs-desktop /opt/IPFS Desktop/locales/es.pak
ipfs-desktop /opt/IPFS Desktop/locales/et.pak
ipfs-desktop /opt/IPFS Desktop/locales/fa.pak
ipfs-desktop /opt/IPFS Desktop/locales/fi.pak
ipfs-desktop /opt/IPFS Desktop/locales/fil.pak
ipfs-desktop /opt/IPFS Desktop/locales/fr.pak
ipfs-desktop /opt/IPFS Desktop/locales/gu.pak
ipfs-desktop /opt/IPFS Desktop/locales/he.pak
ipfs-desktop /opt/IPFS Desktop/locales/hi.pak
ipfs-desktop /opt/IPFS Desktop/locales/hr.pak
ipfs-desktop /opt/IPFS Desktop/locales/hu.pak
ipfs-desktop /opt/IPFS Desktop/locales/id.pak
ipfs-desktop /opt/IPFS Desktop/locales/it.pak
ipfs-desktop /opt/IPFS Desktop/locales/ja.pak
ipfs-desktop /opt/IPFS Desktop/locales/kn.pak
ipfs-desktop /opt/IPFS Desktop/locales/ko.pak
ipfs-desktop /opt/IPFS Desktop/locales/lt.pak
ipfs-desktop /opt/IPFS Desktop/locales/lv.pak
ipfs-desktop /opt/IPFS Desktop/locales/ml.pak
ipfs-desktop /opt/IPFS Desktop/locales/mr.pak
ipfs-desktop /opt/IPFS Desktop/locales/ms.pak
ipfs-desktop /opt/IPFS Desktop/locales/nb.pak
ipfs-desktop /opt/IPFS Desktop/locales/nl.pak
ipfs-desktop /opt/IPFS Desktop/locales/pl.pak
ipfs-desktop /opt/IPFS Desktop/locales/pt-BR.pak
ipfs-desktop /opt/IPFS Desktop/locales/pt-PT.pak
ipfs-desktop /opt/IPFS Desktop/locales/ro.pak
ipfs-desktop /opt/IPFS Desktop/locales/ru.pak
ipfs-desktop /opt/IPFS Desktop/locales/sk.pak
ipfs-desktop /opt/IPFS Desktop/locales/sl.pak
ipfs-desktop /opt/IPFS Desktop/locales/sr.pak
ipfs-desktop /opt/IPFS Desktop/locales/sv.pak
ipfs-desktop /opt/IPFS Desktop/locales/sw.pak
ipfs-desktop /opt/IPFS Desktop/locales/ta.pak
ipfs-desktop /opt/IPFS Desktop/locales/te.pak
ipfs-desktop /opt/IPFS Desktop/locales/th.pak
ipfs-desktop /opt/IPFS Desktop/locales/tr.pak
ipfs-desktop /opt/IPFS Desktop/locales/uk.pak
ipfs-desktop /opt/IPFS Desktop/locales/vi.pak
ipfs-desktop /opt/IPFS Desktop/locales/zh-CN.pak
ipfs-desktop /opt/IPFS Desktop/locales/zh-TW.pak
ipfs-desktop /opt/IPFS Desktop/resources.pak
ipfs-desktop /opt/IPFS Desktop/resources/
ipfs-desktop /opt/IPFS Desktop/resources/app.asar
ipfs-desktop /opt/IPFS Desktop/resources/app.asar.unpacked/
ipfs-desktop /opt/IPFS Desktop/resources/app.asar.unpacked/node_modules/
ipfs-desktop /opt/IPFS Desktop/resources/app.asar.unpacked/node_modules/go-ipfs/
ipfs-desktop /opt/IPFS Desktop/resources/app.asar.unpacked/node_modules/go-ipfs/LICENSE
ipfs-desktop /opt/IPFS Desktop/resources/app.asar.unpacked/node_modules/go-ipfs/go-ipfs/
ipfs-desktop /opt/IPFS Desktop/resources/app.asar.unpacked/node_modules/go-ipfs/go-ipfs/LICENSE
ipfs-desktop /opt/IPFS Desktop/resources/app.asar.unpacked/node_modules/go-ipfs/go-ipfs/LICENSE-APACHE
ipfs-desktop /opt/IPFS Desktop/resources/app.asar.unpacked/node_modules/go-ipfs/go-ipfs/LICENSE-MIT
ipfs-desktop /opt/IPFS Desktop/resources/app.asar.unpacked/node_modules/go-ipfs/go-ipfs/README.md
ipfs-desktop /opt/IPFS Desktop/resources/app.asar.unpacked/node_modules/go-ipfs/go-ipfs/install.sh
ipfs-desktop /opt/IPFS Desktop/resources/app.asar.unpacked/node_modules/go-ipfs/go-ipfs/ipfs
ipfs-desktop /opt/IPFS Desktop/resources/app.asar.unpacked/node_modules/go-ipfs/package.json
ipfs-desktop /opt/IPFS Desktop/resources/app.asar.unpacked/node_modules/go-ipfs/src/
ipfs-desktop /opt/IPFS Desktop/resources/app.asar.unpacked/node_modules/go-ipfs/src/download.js
ipfs-desktop /opt/IPFS Desktop/resources/app.asar.unpacked/node_modules/go-ipfs/src/index.js
ipfs-desktop /opt/IPFS Desktop/resources/app.asar.unpacked/node_modules/go-ipfs/src/post-install.js
ipfs-desktop /opt/IPFS Desktop/resources/app.asar.unpacked/node_modules/go-ipfs/tsconfig.json
ipfs-desktop /opt/IPFS Desktop/resources/app.asar.unpacked/src/
ipfs-desktop /opt/IPFS Desktop/resources/app.asar.unpacked/src/ipfs-on-path/
ipfs-desktop /opt/IPFS Desktop/resources/app.asar.unpacked/src/ipfs-on-path/scripts/
ipfs-desktop /opt/IPFS Desktop/resources/app.asar.unpacked/src/ipfs-on-path/scripts/uninstall.js
ipfs-desktop /opt/IPFS Desktop/resources/app.asar.unpacked/src/ipfs-on-path/scripts/uninstall.ps1
ipfs-desktop /opt/IPFS Desktop/snapshot_blob.bin
ipfs-desktop /opt/IPFS Desktop/swiftshader/
ipfs-desktop /opt/IPFS Desktop/swiftshader/libEGL.so
ipfs-desktop /opt/IPFS Desktop/swiftshader/libGLESv2.so
ipfs-desktop /opt/IPFS Desktop/v8_context_snapshot.bin
ipfs-desktop /opt/IPFS Desktop/vk_swiftshader_icd.json
ipfs-desktop /usr/
ipfs-desktop /usr/bin/
ipfs-desktop /usr/bin/ipfs-desktop
ipfs-desktop /usr/share/
ipfs-desktop /usr/share/applications/
ipfs-desktop /usr/share/applications/ipfs-desktop.desktop
ipfs-desktop /usr/share/icons/
ipfs-desktop /usr/share/icons/hicolor/
ipfs-desktop /usr/share/icons/hicolor/128x128/
ipfs-desktop /usr/share/icons/hicolor/128x128/apps/
ipfs-desktop /usr/share/icons/hicolor/128x128/apps/ipfs-desktop.png
ipfs-desktop /usr/share/icons/hicolor/16x16/
ipfs-desktop /usr/share/icons/hicolor/16x16/apps/
ipfs-desktop /usr/share/icons/hicolor/16x16/apps/ipfs-desktop.png
ipfs-desktop /usr/share/icons/hicolor/256x256/
ipfs-desktop /usr/share/icons/hicolor/256x256/apps/
ipfs-desktop /usr/share/icons/hicolor/256x256/apps/ipfs-desktop.png
ipfs-desktop /usr/share/icons/hicolor/32x32/
ipfs-desktop /usr/share/icons/hicolor/32x32/apps/
ipfs-desktop /usr/share/icons/hicolor/32x32/apps/ipfs-desktop.png
ipfs-desktop /usr/share/icons/hicolor/48x48/
ipfs-desktop /usr/share/icons/hicolor/48x48/apps/
ipfs-desktop /usr/share/icons/hicolor/48x48/apps/ipfs-desktop.png
ipfs-desktop /usr/share/icons/hicolor/512x512/
ipfs-desktop /usr/share/icons/hicolor/512x512/apps/
ipfs-desktop /usr/share/icons/hicolor/512x512/apps/ipfs-desktop.png
ipfs-desktop /usr/share/icons/hicolor/64x64/
ipfs-desktop /usr/share/icons/hicolor/64x64/apps/
ipfs-desktop /usr/share/icons/hicolor/64x64/apps/ipfs-desktop.png
ipfs-desktop /usr/share/licenses/
ipfs-desktop /usr/share/licenses/ipfs-desktop/
ipfs-desktop /usr/share/licenses/ipfs-desktop/LICENSE
ipfs-desktop /usr/share/licenses/ipfs-desktop/LICENSE.electron.txt
ipfs-desktop /usr/share/licenses/ipfs-desktop/LICENSES.chromium.html
```

**Comment by Martinligabue** [comment]
I just hop in to clarify that it only appeared once, and I just pressed the default report button, so maybe it has just to do with and updated file(???) that was changed and while trying to quit the app had an error (I have no clue about how this works, I just hope I can help)

**Comment by RubenKelevra** [comment]
@Martinligabue that's definitely a bug and should not happen. So, thanks for reporting! :)

**Comment by RubenKelevra** [comment]
@lidel looks like this happened before: https://github.com/ipfs/ipfs-desktop/issues/1602

If it's just expecting this one file, I can happily just copy the default png to this location. Question is more: Why does it happen in the first place, as there are icons for this application stored in the right location. :)

**Comment by Martinligabue** [comment]
happened same thing again with the "aur/ipfs-desktop 0.19.1-3 -> 0.19.3-1", 
same exact error code, so I won't open a new issue
I have a screenshot of the update, but it doesn't have any info that seems interesting, no errors or anything so I won't upload it unless you think it might help, I also have the logs, but they say the same thing:
![image](https://user-images.githubusercontent.com/22115672/155239405-ec988832-6e5f-4507-a4de-cb7ae47a8f56.png)

**Comment by lidel** [comment]
@RubenKelevra could be a bug in `electron-builder build --linux pacman`
If you  have time to debug that, go at it, but an easier and more robust fix is to remove custom pacman build via  `electron-build` and reuse upstream distribution-agnostic `.tar.xz` that we already provide (attached to each release).

Just download it  and create AUR package from that (you untar .pacman anyway...)

**Comment by RubenKelevra** [comment]
Well that's not an option here, as we talk about the ipfs-desktop package.

It must be built from the source code as packages which use prebuilt deliverables must use a "-bin" suffix.

**Comment by RubenKelevra** [comment]
And no, I don't have the time to learn anything about debugging the electron builder.

So if ipfs-desktop cannot be built without this bug there's for me the option to orphan (droo) the package in the hopes someone with more time and knowledge picks it up and can fix it, if this has something todo with the build process itself. 

Else I'll just wait for a fix of ipfs-desktop and/or the build toolchain.

**Comment by binvb** [comment]
same error, any progress?   
Error: Failed to load image from path 'C:\Users\Best-User\AppData\Local\Programs\lqb\resources\app.asar\static\collocation.ico
