### ISSUE TITLE
[gui error report]

### ISSUE THREAD

**Issue by denali49** [ipfs/ipfs-desktop#1989]
Please describe what you were doing when this error happened.

Trying to perform update to 0.19 and it is not updating even after several restarts and machine restarts.

**Specifications**

- **OS**: darwin
- **IPFS Desktop Version**: 0.18.1
- **Electron Version**: 13.6.3
- **Chrome Version**: 91.0.4472.164

**Error**

```
TypeError: Object has been destroyed
    at BrowserWindow.n.loadURL (electron/js2c/browser_init.js:33:1767)
    at IpcMainImpl.<anonymous> (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/webui/index.js:137:14)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by lidel** [comment]
See https://github.com/ipfs/ipfs-desktop/issues/1986#issuecomment-1048334952

**Comment by denali49** [comment]
Manual install of v0.19 solved the problem, thanks!

hyperchainlabs.eth.limo
Twitter @HyperchainLabs
