### ISSUE TITLE
[gui error report] SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by avelguenin** [ipfs/ipfs-desktop#2020]
👉️ Please describe what you were doing when this error happened.

Started the application. The error happened several time each time I tried, both with and without the ipfs daemon running. Some of the times I could see the start page (with no indication of the daemon running regardless of whether it was).

**Specifications**

- **OS**: linux
- **IPFS Desktop Version**: 0.20.1
- **Electron Version**: 17.1.0
- **Chrome Version**: 98.0.4758.102

**Error**

```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Daemon._getConfig (/snap/ipfs-desktop/33/resources/app.asar/node_modules/ipfsd-ctl/src/ipfsd-daemon.js:366:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Daemon.init (/snap/ipfs-desktop/33/resources/app.asar/node_modules/ipfsd-ctl/src/ipfsd-daemon.js:158:9)
    at async spawn (/snap/ipfs-desktop/33/resources/app.asar/src/daemon/daemon.js:55:3)
    at async module.exports (/snap/ipfs-desktop/33/resources/app.asar/src/daemon/daemon.js:150:31)
    at async startIpfs (/snap/ipfs-desktop/33/resources/app.asar/src/daemon/index.js:46:17)
    at async module.exports (/snap/ipfs-desktop/33/resources/app.asar/src/daemon/index.js:114:3)
    at async run (/snap/ipfs-desktop/33/resources/app.asar/src/index.js:83:5)
```

**Comment by hacdias** [comment]
Duplicate of #2000
