### ISSUE TITLE
[gui error report] SyntaxError: Unexpected end of JSON input: Error: open /home/chito/snap/

### ISSUE THREAD

**Issue by chitoadinugraha** [ipfs/ipfs-desktop#2057]
Everytime I open IPFS desktop, it closed instantly

**Specifications**

- **OS**: linux
- **IPFS Desktop Version**: 0.20.3
- **Electron Version**: 17.1.0
- **Chrome Version**: 98.0.4758.102

**Error**

```
SyntaxError: Unexpected end of JSON input: Error: open /home/chito/snap/ipfs-desktop/33/.ipfs/config: no such file or directory
    at JSON.parse (<anonymous>)
    at Daemon._getConfig (/snap/ipfs-desktop/35/resources/app.asar/node_modules/ipfsd-ctl/src/ipfsd-daemon.js:368:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Daemon.init (/snap/ipfs-desktop/35/resources/app.asar/node_modules/ipfsd-ctl/src/ipfsd-daemon.js:158:9)
    at async spawn (/snap/ipfs-desktop/35/resources/app.asar/src/daemon/daemon.js:54:3)
    at async module.exports (/snap/ipfs-desktop/35/resources/app.asar/src/daemon/daemon.js:169:31)
    at async startIpfs (/snap/ipfs-desktop/35/resources/app.asar/src/daemon/index.js:46:17)
    at async module.exports (/snap/ipfs-desktop/35/resources/app.asar/src/daemon/index.js:114:3)
    at async run (/snap/ipfs-desktop/35/resources/app.asar/src/index.js:83:5)
```

**Comment by lidel** [comment]
Continued in https://github.com/ipfs/ipfs-desktop/issues/2050
