### ISSUE TITLE
[gui error report] Error: Initializing daemon...

### ISSUE THREAD

**Issue by jonapaniagua** [ipfs/ipfs-desktop#2154]
👉️ Please describe what you were doing when this error happened.

**Specifications**

- **OS**: linux
- **IPFS Desktop Version**: 0.20.6
- **Electron Version**: 18.0.3
- **Chrome Version**: 100.0.4896.75

**Error**

```
Error: Initializing daemon...
go-ipfs version: 0.12.2
Repo version: 12
System version: amd64/linux
Golang version: go1.16.15
2022-05-20T13:25:42.066-0700	ERROR	cmd/ipfs	ipfs/daemon.go:430	error from node construction: expected ed25519 data size to be 64 or 96, got 32
Error: expected ed25519 data size to be 64 or 96, got 32


    at errorTemplate (/home/jonathan/Descargas/ipfs-desktop-0.20.6-linux-x64/resources/app.asar/src/daemon/migration-prompt.js:78:49)
    at loadWindow (/home/jonathan/Descargas/ipfs-desktop-0.20.6-linux-x64/resources/app.asar/src/daemon/migration-prompt.js:115:26)
    at module.exports (/home/jonathan/Descargas/ipfs-desktop-0.20.6-linux-x64/resources/app.asar/src/daemon/migration-prompt.js:120:3)
    at startIpfsWithLogs (/home/jonathan/Descargas/ipfs-desktop-0.20.6-linux-x64/resources/app.asar/src/daemon/daemon.js:165:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (/home/jonathan/Descargas/ipfs-desktop-0.20.6-linux-x64/resources/app.asar/src/daemon/daemon.js:194:17)
    at async startIpfs (/home/jonathan/Descargas/ipfs-desktop-0.20.6-linux-x64/resources/app.asar/src/daemon/index.js:46:17)
    at async module.exports (/home/jonathan/Descargas/ipfs-desktop-0.20.6-linux-x64/resources/app.

**Comment by lidel** [comment]
Please see suggestions mentioned in https://github.com/ipfs/ipfs-desktop/issues/2131#issuecomment-1131693656, closing this one as a duplicate.
