### ISSUE TITLE
[gui error report] Error: Initializing daemon...

### ISSUE THREAD

**Issue by halbodb** [ipfs/ipfs-desktop#2249]
👉️ Please describe what you were doing when this error happened.

**Specifications**

- **OS**: linux
- **IPFS Desktop Version**: 0.23.0
- **Electron Version**: 19.0.9
- **Chrome Version**: 102.0.5005.167

**Error**

```
Error: Initializing daemon...
Kubo version: 0.15.0
Repo version: 12
System version: amd64/linux
Golang version: go1.18.5

Error: lock /home/halbo/snap/ipfs-desktop/40/.ipfs/repo.lock: permission denied

    at errorTemplate (/snap/ipfs-desktop/41/resources/app.asar/src/daemon/migration-prompt.js:78:49)
    at loadWindow (/snap/ipfs-desktop/41/resources/app.asar/src/daemon/migration-prompt.js:129:26)
    at showMigrationPrompt (/snap/ipfs-desktop/41/resources/app.asar/src/daemon/migration-prompt.js:134:3)
    at startIpfsWithLogs (/snap/ipfs-desktop/41/resources/app.asar/src/daemon/daemon.js:193:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async startDaemon (/snap/ipfs-desktop/41/resources/app.asar/src/daemon/daemon.js:216:27)
    at async startIpfs (/snap/ipfs-desktop/41/resources/app.asar/src/daemon/index.js:48:17)
    at async setupDaemon (/snap/ipfs-desktop/41/resources/app.asar/src/daemon/index.js:116:3)
    at async run (/snap/ipfs-desktop/41/resources/app.asar/src/index.js:85:5)
```

**Comment by hacdias** [comment]
Hello. Please follow the instructions in the README for this sort of errors: [ipfs/ipfs-desktop#i-got-a-repolock-error-how-do-i-resolve-this](https://github.com/ipfs/ipfs-desktop#i-got-a-repolock-error-how-do-i-resolve-this).
