### ISSUE TITLE
[gui error report] SyntaxError: Unexpected end of JSON input: Error: open /home/mike/snap/i

### ISSUE THREAD

**Issue by mikezentz** [ipfs/ipfs-desktop#2251]
👉️ Please describe what you were doing when this error happened.

IPFS-Desktop fails at startup and asks if I would like to restart.  Restart just repeats the failure and prompt.

**Specifications**

- **OS**: linux
- **IPFS Desktop Version**: 0.23.0
- **Electron Version**: 19.0.9
- **Chrome Version**: 102.0.5005.167

**Error**

```
SyntaxError: Unexpected end of JSON input: Error: open /home/mike/snap/ipfs-desktop/36/.ipfs/config: no such file or directory
    at JSON.parse (<anonymous>)
    at Daemon._getConfig (/snap/ipfs-desktop/41/resources/app.asar/node_modules/ipfsd-ctl/src/ipfsd-daemon.js:368:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Daemon.init (/snap/ipfs-desktop/41/resources/app.asar/node_modules/ipfsd-ctl/src/ipfsd-daemon.js:158:9)
    at async getIpfsd (/snap/ipfs-desktop/41/resources/app.asar/src/daemon/daemon.js:63:7)
    at async startDaemon (/snap/ipfs-desktop/41/resources/app.asar/src/daemon/daemon.js:210:17)
    at async startIpfs (/snap/ipfs-desktop/41/resources/app.asar/src/daemon/index.js:48:17)
    at async setupDaemon (/snap/ipfs-desktop/41/resources/app.asar/src/daemon/index.js:116:3)
    at async run (/snap/ipfs-desktop/41/resources/app.asar/src/index.js:85:5)
```

**Comment by hacdias** [comment]
Snap has confinement issues. Please uninstall the snap package and use the AppImage. See https://github.com/ipfs/ipfs-desktop/issues/2031
