### ISSUE TITLE
[gui error report] SyntaxError: Unexpected end of JSON input: Error: open /home/talha-amin/

### ISSUE THREAD

**Issue by talha-amin** [ipfs/ipfs-desktop#2292]
👉️ Please describe what you were doing when this error happened.

**Specifications**

- **OS**: linux 5.15.0-48-generic
- **IPFS Desktop Version**: 0.24.0
- **Electron Version**: 19.0.9
- **Chrome Version**: 102.0.5005.167

**Error**

```
SyntaxError: Unexpected end of JSON input: Error: open /home/talha-amin/snap/ipfs-desktop/40/.ipfs/config: no such file or directory
    at JSON.parse (<anonymous>)
    at Daemon._getConfig (/snap/ipfs-desktop/42/resources/app.asar/node_modules/ipfsd-ctl/src/ipfsd-daemon.js:368:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Daemon.init (/snap/ipfs-desktop/42/resources/app.asar/node_modules/ipfsd-ctl/src/ipfsd-daemon.js:158:9)
    at async getIpfsd (/snap/ipfs-desktop/42/resources/app.asar/src/daemon/daemon.js:63:7)
    at async startDaemon (/snap/ipfs-desktop/42/resources/app.asar/src/daemon/daemon.js:210:17)
    at async startIpfs (/snap/ipfs-desktop/42/resources/app.asar/src/daemon/index.js:48:17)
    at async setupDaemon (/snap/ipfs-desktop/42/resources/app.asar/src/daemon/index.js:116:3)
    at async run (/snap/ipfs-desktop/42/resources/app.asar/src/index.js:85:5)
```

**Comment by SgtPooki** [comment]
@talha-amin thanks for submitting this issue! The error message is pretty clear, but I'm confused because the config is supposed to be created by the app on startup.

Can you include the error.log and combined.log files so we can investigate further? Description of their location is at https://github.com/ipfs/ipfs-desktop#where-are-my-ipfs-configuration-and-log-files
