### ISSUE TITLE
[gui error report] SyntaxError: Unexpected end of JSON input: Error: open /home/sorin/snap/

### ISSUE THREAD

**Issue by sorinirimies** [ipfs/ipfs-desktop#2324]
👉️ Please describe what you were doing when this error happened.

**Specifications**

- **OS**: linux 5.15.76-1-MANJARO
- **IPFS Desktop Version**: 0.24.0
- **Electron Version**: 19.0.9
- **Chrome Version**: 102.0.5005.167

**Error**

```
SyntaxError: Unexpected end of JSON input: Error: open /home/sorin/snap/ipfs-desktop/30/.ipfs/config: no such file or directory
    at JSON.parse (<anonymous>)
    at Daemon._getConfig (/snap/ipfs-desktop/42/resources/app.asar/node_modules/ipfsd-ctl/src/ipfsd-daemon.js:368:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Daemon.init (/snap/ipfs-desktop/42/resources/app.asar/node_modules/ipfsd-ctl/src/ipfsd-daemon.js:158:9)
    at async getIpfsd (/snap/ipfs-desktop/42/resources/app.asar/src/daemon/daemon.js:63:7)
    at async startDaemon (/snap/ipfs-desktop/42/resources/app.asar/src/daemon/daemon.js:210:17)
    at async startIpfs (/snap/ipfs-desktop/42/resources/app.asar/src/daemon/index.js:48:17)
    at async setupDaemon (/snap/ipfs-desktop/42/resources/app.asar/src/daemon/index.js:116:3)
    at async run (/snap/ipfs-desktop/42/resources/app.asar/src/index.js:85:5)
```

**Comment by SgtPooki** [comment]
Hey @sorinirimies thanks for submitting this issue!

A few things to note:

1. IPFS Desktop seems to have been installed via snap
2. we no longer support snap installs, as called out in our readme: https://github.com/ipfs/ipfs-desktop#linuxfreebsd

Can you try to install via .AppImage and let us know if you continue to experience this issue?
