### ISSUE TITLE
[gui error report] SyntaxError: Unexpected end of JSON input: Error: open /home/foundation/

### ISSUE THREAD

**Issue by noryev** [ipfs/ipfs-desktop#2360]
👉️ Please describe what you were doing when this error happened.

**Specifications**

- **OS**: linux 5.15.0-56-generic
- **IPFS Desktop Version**: 0.25.0
- **Electron Version**: 19.1.9
- **Chrome Version**: 102.0.5005.167

**Error**

```
SyntaxError: Unexpected end of JSON input: Error: open /home/foundation/snap/ipfs-desktop/42/.ipfs/config: no such file or directory
    at JSON.parse (<anonymous>)
    at Daemon._getConfig (/snap/ipfs-desktop/44/resources/app.asar/node_modules/ipfsd-ctl/src/ipfsd-daemon.js:368:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Daemon.init (/snap/ipfs-desktop/44/resources/app.asar/node_modules/ipfsd-ctl/src/ipfsd-daemon.js:158:9)
    at async getIpfsd (/snap/ipfs-desktop/44/resources/app.asar/src/daemon/daemon.js:63:7)
    at async startDaemon (/snap/ipfs-desktop/44/resources/app.asar/src/daemon/daemon.js:210:17)
    at async startIpfs (/snap/ipfs-desktop/44/resources/app.asar/src/daemon/index.js:48:17)
    at async setupDaemon (/snap/ipfs-desktop/44/resources/app.asar/src/daemon/index.js:116:3)
    at async run (/snap/ipfs-desktop/44/resources/app.asar/src/index.js:85:5)
```

**Comment by noryev** [comment]
I am unsure if it is related but I updated my js-ipfs to kubo and then after trying to open IPFS Desktop on my Ubuntu machine, I get this pop-up every time. 
![Screenshot from 2022-12-14 00-01-28](https://user-images.githubusercontent.com/30084404/207518880-622a8d53-ba18-42fb-af74-388c694c4b71.png)

**Comment by noryev** [comment]
I will try and re-create and see if its still a problem.
