### ISSUE TITLE
[gui error report] SyntaxError: Unexpected end of JSON input: Error: open /home/andrea/snap

### ISSUE THREAD

**Issue by andreacanton** [ipfs/ipfs-desktop#2419]
I've just opened the application.

This is what I see
![image](https://user-images.githubusercontent.com/265536/219973441-479f0e0c-a4fb-4a62-962a-b017038b1eee.png)

Here is the content of the folder `/home/andrea/snap/ipfs-desktop/`:
![image](https://user-images.githubusercontent.com/265536/219973540-bc340e58-d1fb-4d45-af5f-65324d548cc3.png)

**Specifications**

- **OS**: linux 5.10.166-1-MANJARO
- **IPFS Desktop Version**: 0.26.1
- **Electron Version**: 19.1.9
- **Chrome Version**: 102.0.5005.167

**Error**

```
SyntaxError: Unexpected end of JSON input: Error: open /home/andrea/snap/ipfs-desktop/43/.ipfs/config: no such file or directory
    at JSON.parse (<anonymous>)
    at Daemon._getConfig (/snap/ipfs-desktop/46/resources/app.asar/node_modules/ipfsd-ctl/src/ipfsd-daemon.js:368:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Daemon.init (/snap/ipfs-desktop/46/resources/app.asar/node_modules/ipfsd-ctl/src/ipfsd-daemon.js:158:9)
    at async getIpfsd (/snap/ipfs-desktop/46/resources/app.asar/src/daemon/daemon.js:63:7)
    at async startDaemon (/snap/ipfs-desktop/46/resources/app.asar/src/daemon/daemon.js:210:17)
    at async startIpfs (/snap/ipfs-desktop/46/resources/app.asar/src/daemon/index.js:48:17)
    at async setupDaemon (/snap/ipfs-desktop/46/resources/app.asar/src/daemon/index.js:116:3)
    at async run (/snap/ipfs-desktop/46/resources/app.asar/src/index.js:85:5)
```

**Comment by andreacanton** [comment]
update: same error after a `sudo pacman -Syu`
