### ISSUE TITLE
[gui error report] SyntaxError: Unexpected end of JSON input: Error: open /home/josecelano/

### ISSUE THREAD

**Issue by josecelano** [ipfs/ipfs-desktop#2431]
Hi, I've just opened the IPFS desktop after not using it for some months.

**Specifications**

- **OS**: linux 5.10.0-1052-oem
- **IPFS Desktop Version**: 0.26.1
- **Electron Version**: 19.1.9
- **Chrome Version**: 102.0.5005.167

**Error**

```
SyntaxError: Unexpected end of JSON input: Error: open /home/josecelano/snap/ipfs-desktop/42/.ipfs/config: no such file or directory
    at JSON.parse (<anonymous>)
    at Daemon._getConfig (/snap/ipfs-desktop/46/resources/app.asar/node_modules/ipfsd-ctl/src/ipfsd-daemon.js:368:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Daemon.init (/snap/ipfs-desktop/46/resources/app.asar/node_modules/ipfsd-ctl/src/ipfsd-daemon.js:158:9)
    at async getIpfsd (/snap/ipfs-desktop/46/resources/app.asar/src/daemon/daemon.js:63:7)
    at async startDaemon (/snap/ipfs-desktop/46/resources/app.asar/src/daemon/daemon.js:210:17)
    at async startIpfs (/snap/ipfs-desktop/46/resources/app.asar/src/daemon/index.js:48:17)
    at async setupDaemon (/snap/ipfs-desktop/46/resources/app.asar/src/daemon/index.js:116:3)
    at async run (/snap/ipfs-desktop/46/resources/app.asar/src/index.js:85:5)
```

**Comment by josecelano** [comment]
> Thanks for submitting this issue @josecelano, the error seems to describe a missing config that's required, but a few things to note:
> 
> * IPFS Desktop seems to have been installed via snap
> * we no longer support snap installs, as called out in our readme: https://github.com/ipfs/ipfs-desktop#linuxfreebsd
> 
> Can you try to install via .AppImage and let us know if you continue to experience this issue?

Thank you @whizzzkid ! Now I can see the reason:

![image](https://user-images.githubusercontent.com/58816/225550260-2665271a-b2c8-42e3-a836-5798ccd13916.png)

Before I was only able to see the popup window you see at the bottom.

It seems I do not have the daemon. Maybe that's why I upgraded the Ubuntu. Anyway, I will uninstall it and reinstall it using the ".AppImage". I guess I won't have any problem.
