### ISSUE TITLE
[gui error report] Error: write EIO

### ISSUE THREAD

**Issue by gentoober-one** [ipfs/ipfs-desktop#2487]
👉️ Please describe what you were doing when this error happened.

**Specifications**

- **OS**: linux 6.1.22-gentoo-dist
- **IPFS Desktop Version**: 0.28.0
- **Electron Version**: 19.1.9
- **Chrome Version**: 102.0.5005.167

**Error**

```
Error: write EIO
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:795:11)
    at Socket._write (node:net:807:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Writable.write (node:internal/streams/writable:334:10)
    at Console.log (/home/gentoober/IPFS/ipfs-desktop/node_modules/winston/lib/winston/transports/console.js:79:23)
    at Console._write (/home/gentoober/IPFS/ipfs-desktop/node_modules/winston-transport/index.js:82:19)
    at doWrite (/home/gentoober/IPFS/ipfs-desktop/node_modules/winston-transport/node_modules/readable-stream/lib/_stream_writable.js:409:139)
```

**Comment by gentoober-one** [comment]
I apologize for taking up your time! The error did occur, however, there was a pending update for IPFS Desktop. Once I updated it, there were no more issues.

Another thing that may have influenced was the fact that I was using a VPN. I was notified that port 8000 (?) - sorry, I can't remember the exact port - was in use and asked if I wanted to use another port. Upon accepting, everything worked correctly.

Thank you for your attention and for your amazing work! I have been able to get many people to use IPFS and IPFS Desktop as well.

Best regards, Felipe "Gentoober".

Enviado com o e-mail seguro de [Proton Mail](https://proton.me/).

------- Original Message -------
Em quarta-feira, 17 de maio de 2023 às 03:19, Nishant Arora ***@***.***> escreveu:
