### ISSUE TITLE
[gui error report] SyntaxError: Unexpected end of JSON input: Error: open /home/avel/.ipfs/

### ISSUE THREAD

**Issue by avelguenin** [ipfs/ipfs-desktop#2609]
👉️ Please describe what you were doing when this error happened.

I opened the latest .AppImage, made it executable, and launched it. An error message appeared saying the programm crashed and asking me to report the bug.

**Specifications**

- **OS**: linux 6.2.0-26-generic
- **IPFS Desktop Version**: 0.30.1
- **Electron Version**: 19.1.9
- **Chrome Version**: 102.0.5005.167

**Error**

```
SyntaxError: Unexpected end of JSON input: Error: open /home/avel/.ipfs/config: no such file or directory
    at JSON.parse (<anonymous>)
    at Daemon._getConfig (/tmp/.mount_ipfs-dqadKkP/resources/app.asar/node_modules/ipfsd-ctl/src/ipfsd-daemon.js:368:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Daemon.init (/tmp/.mount_ipfs-dqadKkP/resources/app.asar/node_modules/ipfsd-ctl/src/ipfsd-daemon.js:158:9)
    at async getIpfsd (/tmp/.mount_ipfs-dqadKkP/resources/app.asar/src/daemon/daemon.js:63:7)
    at async startDaemon (/tmp/.mount_ipfs-dqadKkP/resources/app.asar/src/daemon/daemon.js:210:17)
    at async startIpfs (/tmp/.mount_ipfs-dqadKkP/resources/app.asar/src/daemon/index.js:49:17)
    at async setupDaemon (/tmp/.mount_ipfs-dqadKkP/resources/app.asar/src/daemon/index.js:116:3)
    at async Promise.all (index 1)
    at async run (/tmp/.mount_ipfs-dqadKkP/resources/app.asar/src/index.js:68:5)
```

**Comment by avelguenin** [comment]
Thank you whizzzkid.

home/avel/.ipfs/config does not exist. My username is not "avel", so home/avel does not exist either. I do not know why the installer tries to access files there.

**Comment by avelguenin** [comment]
Hi @whizzzkid and thank you for your attention. 

Both $HOME and ~ resolve to /home/[username] (where [username] is different from avel). I have restored the save of a previous computer, whose main username was "avel", on the one I'm using now. But I've never had any program try to access or compile in /home/avel, so I'm not sure what's going one here.

`find /home -type d -name ".ipfs"` has no output, and neither does `find /snap -type d -name ".ipfs"`, `find /home -type d -name "ipfs"` or `find /snap -type d -name "ipfs"`. I've checked with ls -ah just in case, and I can't find a .ipfs or ipfs folder anywhere. So if there is indeed a ipfs config file somewhere, I don't know how to access it.

**Comment by avelguenin** [comment]
@whizzzkid All right, now that I've found and deleted the config folder, it seems to run well. Thank you !
