### ISSUE TITLE
macOS: panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by WenjunII** [ipfs/ipfs-desktop#2825]
👉️ Please describe what you were doing when this error happened.

**Specifications**

- **OS**: darwin 23.5.0
- **IPFS Desktop Version**: 0.34.0
- **Electron Version**: 19.1.9
- **Chrome Version**: 102.0.5005.167

**Error**

```
Error: Initializing daemon...
Kubo version: 0.27.0
Repo version: 15
System version: amd64/darwin
Golang version: go1.21.7
panic: runtime error: slice bounds out of range [33554436:80]

goroutine 57 [running]:
internal/poll.(*FD).Write(0xc000b60b80, {0xc000380482, 0x50, 0x200})
	internal/poll/fd_unix.go:380  0x469
net.(*netFD).Write(0xc000b60b80, {0xc000380482?, 0xc0008c8e50?, 0x105aede?})
	net/fd_posix.go:96  0x25
net.(*conn).Write(0xc0002e6058, {0xc000380482?, 0x0?, 0x0?})
	net/net.go:191  0x45
net.dnsPacketRoundTrip({_, _}, _, {{{0x5f, 0x64, 0x6e, 0x73, 0x61, 0x64, 0x64, ...}, ...}, ...}, ...)
	net/dnsclient_unix.go:102  0x9e
net.(*Resolver).exchange(_, {_, _}, {_, _}, {{{0x5f, 0x64, 0x6e, 0x73, 0x61, ...}, ...}, ...}, ...)
	net/dnsclient_unix.go:187  0x528
net.(*Resolver).tryOneName(_, {_, _}, _, {_, _}, _)
	net/dnsclient_unix.go:277  0x466
net.(*Resolver).lookup(_, {_, _}, {_, _}, _, _)
	net/dnsclient_unix.go:444  0x2c5
net.(*Resolver).goLookupTXT(0x696c2e7061727473?, {0x2d1d850?, 0xc000051bd0?}, {0xc001280ae0, 0x20})
	net/lookup.go:845  0x85
net.(*Resolver).lookupTXT(...)
	net/lookup_unix.go:116
net.(*Resolver).LookupTXT(0xc000362738?, {0x2d1d850?,

**Comment by lidel** [comment]
@WenjunII seems this is a known bug in Apple's macOS Sonoma: https://github.com/golang/go/issues/61060#issuecomment-1718384385 

Are you able to 
- make sure you macOS is up-to-date
- manually upgrade to the latest version of IPFS Desktop by downloading it from 0.30 ?
