### ISSUE TITLE
[gui error report] Error: Tray is destroyed

### ISSUE THREAD

**Issue by lanceseidman** [ipfs/ipfs-desktop#2860]
I was trying to launch IPFS Desktop and it needed to switch ports and then the splash screen was stuck forever and couldn't load and used xKILL to kill the UI.

**Specifications**

- **OS**: linux 6.9.3-76060903-generic
- **IPFS Desktop Version**: 0.34.0
- **Electron Version**: 19.1.9
- **Chrome Version**: 102.0.5005.167

**Error**

```
Error: Tray is destroyed
    at /opt/IPFS Desktop/resources/app.asar/src/tray.js:350:12
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /opt/IPFS Desktop/resources/app.asar/src/context.js:105:16
```

**Comment by lidel** [comment]
@lanceseidman Is the problem still present in [the latest version](https://github.com/ipfs/ipfs-desktop/releases/latest)? 
which distribution and desktop environment are you using?
