### ISSUE TITLE
[gui error report] SyntaxError: Unexpected end of JSON input: Error: open /home/btcdev/snap

### ISSUE THREAD

**Issue by Andrej656** [ipfs/ipfs-desktop#2895]
👉️ Please describe what you were doing when this error happened.

**Specifications**

- **OS**: linux 6.8.0-49-generic
- **IPFS Desktop Version**: 0.35.1
- **Electron Version**: 19.1.9
- **Chrome Version**: 102.0.5005.167

**Error**

```
SyntaxError: Unexpected end of JSON input: Error: open /home/btcdev/snap/ipfs-desktop/46/.ipfs/config: no such file or directory
    at JSON.parse (<anonymous>)
    at Daemon._getConfig (/snap/ipfs-desktop/49/resources/app.asar/node_modules/ipfsd-ctl/src/ipfsd-daemon.js:368:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Daemon.init (/snap/ipfs-desktop/49/resources/app.asar/node_modules/ipfsd-ctl/src/ipfsd-daemon.js:158:9)
    at async getIpfsd (/snap/ipfs-desktop/49/resources/app.asar/src/daemon/daemon.js:63:7)
    at async startDaemon (/snap/ipfs-desktop/49/resources/app.asar/src/daemon/daemon.js:210:17)
    at async startIpfs (/snap/ipfs-desktop/49/resources/app.asar/src/daemon/index.js:49:17)
    at async setupDaemon (/snap/ipfs-desktop/49/resources/app.asar/src/daemon/index.js:116:3)
    at async Promise.all (index 1)
    at async run (/snap/ipfs-desktop/49/resources/app.asar/src/index.js:68:5)
```

**Comment by lidel** [comment]
iiuc this report the app is running from snap revision 49 while the saved repo path still points inside revision 46, so the config is no longer there. That is snap's strict confinement giving each revision its own home, tracked in #2031, so closing this as a duplicate of that one.

The way out is a package that keeps the repo in a plain `~/.ipfs`: the AppImage or the deb from https://github.com/ipfs/ipfs-desktop/releases/latest. Your old data should still be under `~/snap/ipfs-desktop/46/.ipfs`, so copy that directory across before you remove the snap if you want to keep it.
