### ISSUE TITLE
[gui error report] Error: write EPIPE

### ISSUE THREAD

**Issue by fxhart** [ipfs/ipfs-desktop#2902]
I wasn't doing anything.  Laptop was next to me and the error popped up

- **Desktop**: 0.40.0
- **OS**: linux 6.11.0-061100-generic x64
- **Electron**: 33.2.0
- **Chrome**: 130.0.6723.118

```
Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:161:15)
    at writeGeneric (node:internal/stream_base_commons:152:3)
    at Socket._writeGeneric (node:net:954:11)
    at Socket._write (node:net:966:8)
    at writeOrBuffer (node:internal/streams/writable:570:12)
    at _write (node:internal/streams/writable:499:10)
    at Writable.write (node:internal/streams/writable:508:10)
    at Console.log (/tmp/.mount_ipfs_d7g08QH/resources/app.asar/node_modules/winston/lib/winston/transports/console.js:79:23)
    at Console._write (/tmp/.mount_ipfs_d7g08QH/resources/app.asar/node_modules/winston/node_modules/winston-transport/index.js:82:19)
    at doWrite (/tmp/.mount_ipfs_d7g08QH/resources/app.asar/node_modules/winston/node_modules/winston-transport/node_modules/readable-stream/lib/_stream_writable.js:409:139)
```

**Comment by lidel** [comment]
@fxhart this is a permission/logging problem. IPFS Desktop keeps writing log lines to its output. If that output goes away, a terminal you closed for example, the next log line fails with `EPIPE` and you get this popup.

You are on 0.40.0, which is well behind. Please install the latest release and start the app from your desktop menu rather than a terminal: https://github.com/ipfs/ipfs-desktop/releases/latest

Closing. If it comes back on the latest release, please open a new issue and say how you start the app.
